// Sample Data for the application

// Acceptable user roles
export const ACCEPTABLE_ROLES = ["user", "admin", "moderator", "editor"];

// Sample Products Data
export let products = [
  {
    id: 1,
    name: "MacBook Pro",
    price: 1999,
    category: "Electronics",
    stock: 10,
  },
  { id: 2, name: "iPhone 15", price: 999, category: "Electronics", stock: 25 },
  {
    id: 3,
    name: "Ergonomic Chair",
    price: 299,
    category: "Furniture",
    stock: 15,
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    price: 150,
    category: "Peripherals",
    stock: 30,
  },
  {
    id: 5,
    name: "Gaming Mouse",
    price: 80,
    category: "Peripherals",
    stock: 50,
  },
  { id: 6, name: "4K Monitor", price: 400, category: "Electronics", stock: 12 },
  { id: 7, name: "Standing Desk", price: 550, category: "Furniture", stock: 8 },
  {
    id: 8,
    name: "Noise Cancelling Headphones",
    price: 350,
    category: "Audio",
    stock: 20,
  },
  {
    id: 9,
    name: "Smart Watch",
    price: 250,
    category: "Electronics",
    stock: 40,
  },
  { id: 10, name: "USB-C Hub", price: 60, category: "Accessories", stock: 100 },
  {
    id: 11,
    name: "iPad Pro",
    price: 1099,
    category: "Electronics",
    stock: 18,
  },
  {
    id: 12,
    name: "Wireless Charger",
    price: 45,
    category: "Accessories",
    stock: 75,
  },
  {
    id: 13,
    name: "External SSD 1TB",
    price: 120,
    category: "Storage",
    stock: 35,
  },
  {
    id: 14,
    name: "Webcam HD",
    price: 89,
    category: "Peripherals",
    stock: 22,
  },
  {
    id: 15,
    name: "Bluetooth Speaker",
    price: 180,
    category: "Audio",
    stock: 28,
  },
  {
    id: 16,
    name: "Laptop Stand",
    price: 70,
    category: "Accessories",
    stock: 45,
  },
  {
    id: 17,
    name: "Ergonomic Mouse Pad",
    price: 35,
    category: "Peripherals",
    stock: 60,
  },
  {
    id: 18,
    name: "LED Desk Lamp",
    price: 95,
    category: "Furniture",
    stock: 20,
  },
  {
    id: 19,
    name: "Portable Hard Drive 2TB",
    price: 150,
    category: "Storage",
    stock: 25,
  },
  {
    id: 20,
    name: "Gaming Headset",
    price: 200,
    category: "Audio",
    stock: 15,
  },
  {
    id: 21,
    name: "Dell XPS 15",
    price: 1799,
    category: "Electronics",
    stock: 8,
  },
  {
    id: 22,
    name: "Samsung Galaxy S24",
    price: 899,
    category: "Electronics",
    stock: 20,
  },
  {
    id: 23,
    name: "Office Chair Executive",
    price: 450,
    category: "Furniture",
    stock: 12,
  },
  {
    id: 24,
    name: "USB Flash Drive 128GB",
    price: 25,
    category: "Storage",
    stock: 100,
  },
  {
    id: 25,
    name: "Monitor Light Bar",
    price: 65,
    category: "Accessories",
    stock: 30,
  },
];

// Sample Users Data
export let users = [
  {
    id: 1,
    username: "alex_pro",
    email: "alex.pro@example.com",
    role: "admin",
    age: 30,
  },
  {
    id: 2,
    username: "sarah_j",
    email: "sarah.j@example.com",
    role: "user",
    age: 26,
  },
  {
    id: 3,
    username: "mike_coder",
    email: "mike.c@example.com",
    role: "moderator",
    age: 45,
  },
  {
    id: 4,
    username: "emily_w",
    email: "emily.w@example.com",
    role: "user",
    age: 13,
  },
  {
    id: 5,
    username: "chris_t",
    email: "chris.t@example.com",
    role: "user",
    age: 16,
  },
  {
    id: 6,
    username: "jessica_r",
    email: "jessica.r@testmail.com",
    role: "editor",
    age: 22,
  },
  {
    id: 7,
    username: "ryan_dev",
    email: "ryan.dev@example.com",
    role: "user",
    age: 34,
  },
  {
    id: 8,
    username: "laura_b",
    email: "laura.b@provider.com",
    role: "admin",
    age: 29,
  },
  {
    id: 9,
    username: "kevin_s",
    email: "kevin.s@example.com",
    role: "user",
    age: 41,
  },
  {
    id: 10,
    username: "olivia_m",
    email: "olivia.m@test.com",
    role: "moderator",
    age: 37,
  },
  {
    id: 11,
    username: "david_k",
    email: "david.k@example.com",
    role: "user",
    age: 28,
  },
  {
    id: 12,
    username: "sophia_l",
    email: "sophia.l@testmail.com",
    role: "editor",
    age: 31,
  },
  {
    id: 13,
    username: "james_p",
    email: "james.p@example.com",
    role: "user",
    age: 19,
  },
  {
    id: 14,
    username: "emma_w",
    email: "emma.w@provider.com",
    role: "moderator",
    age: 25,
  },
  {
    id: 15,
    username: "liam_r",
    email: "liam.r@example.com",
    role: "user",
    age: 33,
  },
  {
    id: 16,
    username: "olivia_s",
    email: "olivia.s@test.com",
    role: "admin",
    age: 27,
  },
  {
    id: 17,
    username: "noah_t",
    email: "noah.t@example.com",
    role: "user",
    age: 22,
  },
  {
    id: 18,
    username: "ava_m",
    email: "ava.m@testmail.com",
    role: "editor",
    age: 35,
  },
  {
    id: 19,
    username: "william_j",
    email: "william.j@provider.com",
    role: "user",
    age: 40,
  },
  {
    id: 20,
    username: "charlotte_b",
    email: "charlotte.b@example.com",
    role: "moderator",
    age: 24,
  },
  {
    id: 21,
    username: "ben_c",
    email: "ben.c@example.com",
    role: "user",
    age: 38,
  },
  {
    id: 22,
    username: "mia_h",
    email: "mia.h@testmail.com",
    role: "admin",
    age: 29,
  },
  {
    id: 23,
    username: "ethan_g",
    email: "ethan.g@provider.com",
    role: "user",
    age: 21,
  },
  {
    id: 24,
    username: "amelia_f",
    email: "amelia.f@example.com",
    role: "editor",
    age: 32,
  },
  {
    id: 25,
    username: "lucas_d",
    email: "lucas.d@test.com",
    role: "user",
    age: 36,
  },
];
